mongodb:
  enable: false
  db_host: sht_mongodb
  db_port: 27017
  connection_string: "mongodb+srv://"
  use_conn_str: false
mysql:
  enable: true
  #  host: sht_mysql
  host: localhost
  #  host: 172.29.108.52
  port: 3306
  user: root
  password: "root"
  db: sehuatang

sehuatang:
  # åŸŸå
  domain_name: sehuatang.org
  cookie: "cPNj_2132_saltkey=jPh8px1f; _safe=vqd37pjm4p5uodq339yzk6b7jdt6oich"
  # æ¿å—id
  fid:
    #    103: é«˜æ¸…ä¸­æ–‡å­—å¹•
    #    104: ç´ äººæœ‰ç ç³»åˆ—
    #    37: äºšæ´²æœ‰ç åŸåˆ›
    36: äºšæ´²æ— ç åŸåˆ›
  #    39: åŠ¨æ¼«åŸåˆ›
  #    160: vr
  #    151: 4k
  #    2: å›½äº§åŸåˆ›
  #    38: æ¬§ç¾æ— ç 
  #      107: ä¸‰çº§å†™çœŸ
  #    152: éŸ©å›½ä¸»æ’­

  #  æ›´å…·æ ‡ç­¾å†æ¬¡ç­›é€‰
  typeid:
    103:
      481: æ— ç é«˜æ¸…

  exclude:
    - "ç ´è§£"

  # æŠ“å–é¡µæ•°ï¼Œ10ä»£è¡¨page_start-10 + page_starté¡µ
  page_num: 10
  # æŠ“å–å¼€å§‹é¡µæ•°ï¼Œå¦‚æœä¸ºç©ºåˆ™æ˜¯ç¬¬ä¸€é¡µå¼€å§‹ ä¸èƒ½è®¾ç½®å°äºç­‰äº0
  page_start: 1
  # æŠ“å–æ—¥æœŸ(æ ¼å¼: yyyy-mm-dd), å¦‚æœä¸ºç©º, åˆ™æŠ“å–å½“å‰æ—¥æœŸï¼Œæ”¯æŒæ­£åˆ™åŒ¹é…ï¼Œå¯è¾“å…¥ yyyy-mm æŠ“å–æŒ‡å®šæœˆä»½çš„æ‰€æœ‰æ—¥æœŸ
  date: '\d{4}-\d{2}-\d{2}'

# è®¿é—®é—´éš”
deletime:
  enable: true
  # å¤šå°‘ä¸ªåç­‰å¾…
  num: 30
  # ç­‰å¾…çš„æ—¶é—´
  time: 1

proxy:
  # ä»£ç†æœåŠ¡å™¨
  proxy_host: http://127.0.0.1:11223
  # æ˜¯å¦ä½¿ç”¨ä»£ç†
  proxy_enable: false

sendMessage:
  # æ˜¯å¦å‘é€æ¶ˆæ¯
  send_wecom_enable: false
  # ä¼ä¸šID
  corp_id:
  # åº”ç”¨çš„å‡­è¯å¯†é’¥
  corp_secret:
  # åº”ç”¨ID
  agent_id:
  # mpnewsæ¶ˆæ¯ç±»å‹é¡µé¢å›¾ç‰‡media_idï¼Œéœ€è¦æå‰å°†å›¾ç‰‡ä¸Šä¼ åˆ°ä¼ä¸šå¾®ä¿¡ç´ æåº“ï¼Œæ¥å£è¿”å›media_idï¼Œä¸å¡«åˆ™é»˜è®¤å‘æ–‡æœ¬æ¶ˆæ¯
  media_id:
  # æ¥æ”¶çš„ç”¨æˆ·ï¼Œå¤šä¸ªç”¨æˆ·ç”¨|åˆ†éš”(å¦‚: use1|user2|user3)
  to_user: "@all"
  # telegram æ¨é€
  send_telegram_enable: false
  tg_bot_token: 6526758014:AAHbkjS6ns9VvHwOiKE-Jzz2ldQ_GWP10pk
  tg_chat_id: 5469426795

pikpak:
  pathclassification: false
  enable: true

  # è‰²èŠ±ç³– ä¸€
  # username: himiren433@picvw.com # é‚€è¯·ç  85147854
  # password: poi098

  # username: nawiney632@vip4e.com # é‚€è¯·ç  98105081

  # username: basolep882@telvetto.com # é‚€è¯·ç  34773783

  # å­˜äº† JAV â€¢ åˆé›†ä¸€
  # https://mypikpak.com/s/VNSkLdbYCVr60cvXH2SFHFZMo1
  # å¤§å° â€¢ 9.30 TB
  # username: wiwaret166@talmetry.com # é‚€è¯·ç  95370395 

  # SukebeiEnyoåˆé›†ä¸€
  # â›“ é“¾æ¥ â€¢ https://mypikpak.com/s/VNTS5lxi8GICdZuOHFMs6v62o1
  # ğŸ’¿ å¤§å° â€¢ 7.39 TB
  # username: vepahe1532@roborena.com # é‚€è¯·ç  74553676

  # è‰²èŠ±å ‚ ä¸‰çº§
  # username: weyel44478@namewok.com # é‚€è¯·ç  92196679

  # è‰²èŠ±ç³– äºšæ´²æ— ç åŸåˆ› æ— ç ´è§£
  username: lopipi9801@giratex.com # é‚€è¯·ç  39576161
  password: 098poi
  
  # sosodo9351@dovesilo.com SexAer

# å®šæ—¶ä»»åŠ¡
schedule_time:
  - "11:00"
  - "19:00"
#  - 03:00
#  - 04:00


